#!/bin/bash
if [ -z "$DISPLAY" ]; then
	export DISPLAY=:0
fi
sudo plymouthd --debug --debug-file=/tmp/plymouth-debug-out
sudo plymouth --show-splash
for ((I=0;I<10;I++)); do
  sleep 1
  sudo plymouth --update=event$I
done
sudo plymouth --quit
