#!/bin/bash

# This currently assumes you are using a 4GB thumb drive.
# TODO support any size thumbdrive

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 0
fi

if [ "backup" == "$1" ]; then
    if [ -z "$2" ]; then
        echo "Usage `basename $0` backup /path/to/backup.img" 1>&2
        exit 0
    fi
fi

if [ -z "$1" ]; then
    echo "Usage `basename $0` (backup) /path/to/dd.img" 1>&2
    exit 0
fi

if [ ! -f "$1" ]; then
    echo "Input disk image file does not exist. Check your path." 1>&2
    exit 0
fi

if [ "$2" == "backup" ]; then
    echo "The following drives will be backed up: "
    fdisk -l | /bin/grep 4026
    read -p "Are you sure? Type yes to continue. " SURE

    if [ "yes" == "$SURE" ]; then
        fdisk -l | /bin/grep 4026 | grep -o '/dev/sd[a-z0-9]*' | xargs -P 8 -i dd if={} of=$2 bs=1M
    fi
else
    echo "The following drives will be flashed. All data on them will be lost."
    fdisk -l | /bin/grep 4026
    read -p "Are you sure? Type yes to continue. " SURE

    if [ "yes" == "$SURE" ]; then
        fdisk -l | /bin/grep 4026 | grep -o '/dev/sd[a-z0-9]*' | xargs -P 8 -i dd if=$1 of={} bs=1M
    fi
fi
